stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project DefibrillatorStatusApp.xcodeproj -scheme DefibrillatorStatusApp | xcpretty
    - xcodebuild test -project DefibrillatorStatusApp.xcodeproj -scheme DefibrillatorStatusApp -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.3' | xcpretty -s
  tags:
    - ios