stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project DefibrillatorStatusApp.xcodeproj -scheme DefibrillatorStatusApp | xcpretty
    - xcodebuild test -project DefibrillatorStatusApp.xcodeproj -scheme DefibrillatorStatusApp | xcpretty -c && exit ${PIPESTATUS[0]}
  tags:
    - ios